version: "3.8"

services:
    postgres:
        container_name: postgres
        image: postgres:17
        environment:
            POSTGRES_DB: laravel_docker
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - backend
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5

    api:
        container_name: laravel
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        depends_on:
            - postgres

    webserver:
        container_name: nginx
        image: nginx:stable-alpine
        volumes:
            - .:/var/www/html
            - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "9001:9001"
        networks:
            - backend
        depends_on:
            - api

networks:
    backend:

volumes:
    postgres_data:
    api_data:
